image: rust:1.67
definitions:
  caches:
    apt-lists: /var/lib/apt/lists
    apt-cache: /var/cache/apt

pipelines:
  branches:
    main:
      - step:
          name: 'Build and test'
          script:
            - rm /etc/apt/apt.conf.d/docker-clean
            - apt update
            - apt install -y -q pkg-config libx11-dev libasound2-dev libudev-dev
            - rustup component add clippy-preview
            - cargo clippy --release  # Build main project library
            - cargo test --release    # Build tests and examples
          artifacts: 
            - /target/release/libtomt_bevycss.rlib
