image: rust:1.67

pipelines:
  default:
    - step:
        name: "Install dependencies"
        script:
          - apt update
          - apt install pkg-config libx11-dev libasound2-dev libudev-dev
    - step:
        name: 'Build and test'
        script:
          - cargo test
    - step:
        name: 'Lint with clippy'
        script:
          - cargo install clippy
          - cargo clippy
