[package]
name = "bevy_ecss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8", features = ["filesystem_watcher"]}
cssparser = "0.29"
heck = "0.4"

smallvec = { version = "1.6", features = ["serde", "union", "const_generics"] }

[[example]]
name = "simple_ui"
path = "examples/simple_ui.rs"

[[example]]
name = "apply_on_load"
path = "examples/apply_on_load.rs"

[[example]]
name = "stress_test"
path = "examples/stress_test.rs"