[package]
name = "bevy_ecss"
version = "0.1.0"
edition = "2021"
categories = ["game-engines", "ui", "css", "bevy", "ecs"]
description = "Allows using a subset of CSS to interact with Bevy ECS"
exclude = [".github/"]
keywords = ["css", "bevy", "style", "bevy", "theme", "ui"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/afonsolage/bevy_ecss"


[dependencies]
bevy = { version = "0.8" }
cssparser = "0.29"

smallvec = { version = "1.6", features = ["serde", "union", "const_generics"] }

[dev-dependencies]
bevy = { version = "0.8", features = ["filesystem_watcher"] }

[[example]]
name = "simple_ui"
path = "examples/simple_ui.rs"

[[example]]
name = "hot_reload"
path = "examples/hot_reload.rs"

[[example]]
name = "stress_test"
path = "examples/stress_test.rs"

[[example]]
name = "theme"
path = "examples/theme.rs"
